import pandas as pd
import matplotlib.pyplot as plt

# 1. Read the CSV data generated by the C program
try:
    df = pd.read_csv('benchmark_results.csv')
except FileNotFoundError:
    print("Error: 'benchmark_results.csv' not found. Please run the C program first.")
    exit(1)

# 2. Setup the plot
plt.figure(figsize=(10, 6))

# 3. Plot both algorithmic times against the array size
plt.plot(df['Size'], df['MergeSort_Time'], marker='o', label='Standard 2-Way Merge Sort', color='#1f77b4', linewidth=2)
plt.plot(df['Size'], df['ModifiedMergeSort_Time'], marker='s', label='Modified 3-Way Merge Sort', color='#ff7f0e', linewidth=2)

# 4. Add labels, title, and formatting
plt.title('Performance Comparison: 2-Way vs 3-Way Merge Sort', fontsize=14, pad=15)
plt.xlabel('Array Size (N)', fontsize=12)
plt.ylabel('Execution Time (Seconds)', fontsize=12)

# Standard grid lines for a linear scale
plt.grid(True, linestyle="--", alpha=0.6)
plt.legend(fontsize=11)
plt.tight_layout()

# 5. Save the figure as an image and display it
plt.savefig('merge_sort_plot.png', dpi=300)
print("Plot successfully saved as 'merge_sort_plot.png'")
plt.show()